DEFAULT_SOURCES = [
    {"Source Name": "Apify Google Maps", "Website": "apify.com/compass/crawler-google-places", "Category": "Primary Lead Source", "Geography": "Global", "Industry Focus": "General", "Active": "TRUE", "Search Method": "TMCP Apify Rotate", "Priority": "0", "Notes": "Structured business names, websites, phones, categories, and addresses"},
    {"Source Name": "Yelp", "Website": "yelp.com", "Category": "Business Directory", "Geography": "Global", "Industry Focus": "General", "Active": "TRUE", "Search Method": "Google site search", "Priority": "1", "Notes": "Local businesses and public phone details"},
    {"Source Name": "Yellow Pages US", "Website": "yellowpages.com", "Category": "Business Directory", "Geography": "United States", "Industry Focus": "General", "Active": "TRUE", "Search Method": "Google site search", "Priority": "1", "Notes": "Local business directory"},
    {"Source Name": "Yellow Pages Canada", "Website": "yellowpages.ca", "Category": "Business Directory", "Geography": "Canada", "Industry Focus": "General", "Active": "TRUE", "Search Method": "Google site search", "Priority": "1", "Notes": "Local business directory"},
    {"Source Name": "BBB", "Website": "bbb.org", "Category": "Business Directory", "Geography": "United States/Canada", "Industry Focus": "General", "Active": "TRUE", "Search Method": "Google site search", "Priority": "2", "Notes": "Established business profiles"},
    {"Source Name": "Chamber of Commerce", "Website": "chamberofcommerce.com", "Category": "Business Directory", "Geography": "United States", "Industry Focus": "General", "Active": "TRUE", "Search Method": "Google site search", "Priority": "2", "Notes": "Local company profiles"},
    {"Source Name": "Facebook Business Pages", "Website": "facebook.com", "Category": "Social Directory", "Geography": "Global", "Industry Focus": "General", "Active": "TRUE", "Search Method": "Google site search", "Priority": "3", "Notes": "Can reveal businesses without an independent website"},
    {"Source Name": "Clutch", "Website": "clutch.co", "Category": "Company Directory", "Geography": "Global", "Industry Focus": "B2B", "Active": "TRUE", "Search Method": "Google site search", "Priority": "3", "Notes": "B2B company profiles"},
]
